name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build
        id: build
        run: go run -v .

      - name: Checksum
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geosite-full.db > geosite-full.db.sha256sum
          sha256sum geosite-lite.db > geosite-lite.db.sha256sum

      - name: Release
        if: steps.build.outputs.skip != 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.build.outputs.tag }}
          tag_name: ${{ steps.build.outputs.tag }}
          files: |
            geosite-full.db
            geosite-full.db.sha256sum
            geosite-full.txt
            geosite-lite.db
            geosite-lite.db.sha256sum
            geosite-lite.txt

      - name: Prune Release
        if: steps.build.outputs.skip != 'true'
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
