name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - id: build
        run: go run -v .

      - if: steps.build.outputs.skip != 'true'
        run: sha256sum geosite.db > geosite.db.sha256sum

      - if: steps.build.outputs.skip != 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.build.outputs.tag }}
          tag_name: ${{ steps.build.outputs.tag }}
          files: |
            geosite.db
            geosite.db.sha256sum
